/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * API Do e-cornance
 * OpenAPI spec version: 1.0.0
 */
/** biome-ignore-all assist/source/organizeImports: auto-genrated */

import { useMutation, useQuery } from "@tanstack/vue-query";
import type {
	DataTag,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UseMutationOptions,
	UseMutationReturnType,
	UseQueryOptions,
	UseQueryReturnType,
} from "@tanstack/vue-query";

import * as axios from "axios";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";

import { computed, unref } from "vue";
import type { MaybeRef } from "vue";

import type {
	GetProdutoStatusIdJob200,
	GetProdutoStatusIdJob404,
	PostProdutoRetry200,
	PostProdutoRetry400,
	PostProdutoRetry404,
	PostProdutoRetryBody,
} from "../index.schemas";

/**
 * status da remoção da imagem
 */
export const getProdutoStatusIdJob = (
	idJob: MaybeRef<number>,
	options?: AxiosRequestConfig,
): Promise<AxiosResponse<GetProdutoStatusIdJob200>> => {
	idJob = unref(idJob);

	return axios.default.get(
		`http://127.0.0.1:1234/produto/status/${idJob}`,
		options,
	);
};

export const getGetProdutoStatusIdJobQueryKey = (idJob: MaybeRef<number>) => {
	return ["http:", "127.0.0.1:1234", "produto", "status", idJob] as const;
};

export const getGetProdutoStatusIdJobQueryOptions = <
	TData = Awaited<ReturnType<typeof getProdutoStatusIdJob>>,
	TError = AxiosError<GetProdutoStatusIdJob404>,
>(
	idJob: MaybeRef<number>,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getProdutoStatusIdJob>>,
				TError,
				TData
			>
		>;
		axios?: AxiosRequestConfig;
	},
) => {
	const { query: queryOptions, axios: axiosOptions } = options ?? {};

	const queryKey = getGetProdutoStatusIdJobQueryKey(idJob);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getProdutoStatusIdJob>>
	> = ({ signal }) => getProdutoStatusIdJob(idJob, { signal, ...axiosOptions });

	return {
		queryKey,
		queryFn,
		enabled: computed(
			() => unref(idJob) !== null && unref(idJob) !== undefined,
		),
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof getProdutoStatusIdJob>>,
		TError,
		TData
	>;
};

export type GetProdutoStatusIdJobQueryResult = NonNullable<
	Awaited<ReturnType<typeof getProdutoStatusIdJob>>
>;
export type GetProdutoStatusIdJobQueryError =
	AxiosError<GetProdutoStatusIdJob404>;

export function useGetProdutoStatusIdJob<
	TData = Awaited<ReturnType<typeof getProdutoStatusIdJob>>,
	TError = AxiosError<GetProdutoStatusIdJob404>,
>(
	idJob: MaybeRef<number>,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getProdutoStatusIdJob>>,
				TError,
				TData
			>
		>;
		axios?: AxiosRequestConfig;
	},
	queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetProdutoStatusIdJobQueryOptions(idJob, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = unref(queryOptions).queryKey as DataTag<
		QueryKey,
		TData,
		TError
	>;

	return query;
}

/**
 * refaz o job mal-sucedido
 */
export const postProdutoRetry = (
	postProdutoRetryBody: MaybeRef<PostProdutoRetryBody>,
	options?: AxiosRequestConfig,
): Promise<AxiosResponse<PostProdutoRetry200>> => {
	postProdutoRetryBody = unref(postProdutoRetryBody);

	return axios.default.post(
		`http://127.0.0.1:1234/produto/retry`,
		postProdutoRetryBody,
		options,
	);
};

export const getPostProdutoRetryMutationOptions = <
	TError = AxiosError<PostProdutoRetry400 | PostProdutoRetry404>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postProdutoRetry>>,
		TError,
		{ data: PostProdutoRetryBody },
		TContext
	>;
	axios?: AxiosRequestConfig;
}): UseMutationOptions<
	Awaited<ReturnType<typeof postProdutoRetry>>,
	TError,
	{ data: PostProdutoRetryBody },
	TContext
> => {
	const mutationKey = ["postProdutoRetry"];
	const { mutation: mutationOptions, axios: axiosOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, axios: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postProdutoRetry>>,
		{ data: PostProdutoRetryBody }
	> = (props) => {
		const { data } = props ?? {};

		return postProdutoRetry(data, axiosOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type PostProdutoRetryMutationResult = NonNullable<
	Awaited<ReturnType<typeof postProdutoRetry>>
>;
export type PostProdutoRetryMutationBody = PostProdutoRetryBody;
export type PostProdutoRetryMutationError = AxiosError<
	PostProdutoRetry400 | PostProdutoRetry404
>;

export const usePostProdutoRetry = <
	TError = AxiosError<PostProdutoRetry400 | PostProdutoRetry404>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof postProdutoRetry>>,
			TError,
			{ data: PostProdutoRetryBody },
			TContext
		>;
		axios?: AxiosRequestConfig;
	},
	queryClient?: QueryClient,
): UseMutationReturnType<
	Awaited<ReturnType<typeof postProdutoRetry>>,
	TError,
	{ data: PostProdutoRetryBody },
	TContext
> => {
	return useMutation(getPostProdutoRetryMutationOptions(options), queryClient);
};
