/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * API Do e-cornance
 * OpenAPI spec version: 1.0.0
 */
/** biome-ignore-all assist/source/organizeImports: auto-genrated */

import { useMutation, useQuery } from "@tanstack/vue-query";
import type {
	DataTag,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UseMutationOptions,
	UseMutationReturnType,
	UseQueryOptions,
	UseQueryReturnType,
} from "@tanstack/vue-query";

import * as axios from "axios";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";

import { computed, unref } from "vue";
import type { MaybeRef } from "vue";

import type {
	GetProduto200,
	GetProdutoParams,
	GetProdutoSearch200Item,
	GetProdutoSearchParams,
	GetProdutoSlug200,
	GetProdutoSlug404,
	PostProduto200,
	PostProduto401,
	PostProdutoBody,
	PostProdutoIdProdutoComments200,
	PostProdutoIdProdutoComments401,
	PostProdutoIdProdutoCommentsBody,
	PostProdutoIdProdutoImages200,
	PostProdutoIdProdutoImages400,
	PostProdutoIdProdutoImagesBody,
} from "../index.schemas";

/**
 * Rota de cadastro de produtos
 */
export const postProduto = (
	postProdutoBody: MaybeRef<PostProdutoBody>,
	options?: AxiosRequestConfig,
): Promise<AxiosResponse<PostProduto200>> => {
	postProdutoBody = unref(postProdutoBody);

	return axios.default.post(
		`http://127.0.0.1:1234/produto/`,
		postProdutoBody,
		options,
	);
};

export const getPostProdutoMutationOptions = <
	TError = AxiosError<PostProduto401>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postProduto>>,
		TError,
		{ data: PostProdutoBody },
		TContext
	>;
	axios?: AxiosRequestConfig;
}): UseMutationOptions<
	Awaited<ReturnType<typeof postProduto>>,
	TError,
	{ data: PostProdutoBody },
	TContext
> => {
	const mutationKey = ["postProduto"];
	const { mutation: mutationOptions, axios: axiosOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, axios: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postProduto>>,
		{ data: PostProdutoBody }
	> = (props) => {
		const { data } = props ?? {};

		return postProduto(data, axiosOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type PostProdutoMutationResult = NonNullable<
	Awaited<ReturnType<typeof postProduto>>
>;
export type PostProdutoMutationBody = PostProdutoBody;
export type PostProdutoMutationError = AxiosError<PostProduto401>;

export const usePostProduto = <
	TError = AxiosError<PostProduto401>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof postProduto>>,
			TError,
			{ data: PostProdutoBody },
			TContext
		>;
		axios?: AxiosRequestConfig;
	},
	queryClient?: QueryClient,
): UseMutationReturnType<
	Awaited<ReturnType<typeof postProduto>>,
	TError,
	{ data: PostProdutoBody },
	TContext
> => {
	return useMutation(getPostProdutoMutationOptions(options), queryClient);
};
/**
 * Retorna um Conjunto de 10 Produtos
 */
export const getProduto = (
	params?: MaybeRef<GetProdutoParams>,
	options?: AxiosRequestConfig,
): Promise<AxiosResponse<GetProduto200>> => {
	params = unref(params);

	return axios.default.get(`http://127.0.0.1:1234/produto/`, {
		...options,
		params: { ...unref(params), ...options?.params },
	});
};

export const getGetProdutoQueryKey = (params?: MaybeRef<GetProdutoParams>) => {
	return [
		"http:",
		"127.0.0.1:1234",
		"produto",
		...(params ? [params] : []),
	] as const;
};

export const getGetProdutoQueryOptions = <
	TData = Awaited<ReturnType<typeof getProduto>>,
	TError = AxiosError<unknown>,
>(
	params?: MaybeRef<GetProdutoParams>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getProduto>>, TError, TData>
		>;
		axios?: AxiosRequestConfig;
	},
) => {
	const { query: queryOptions, axios: axiosOptions } = options ?? {};

	const queryKey = getGetProdutoQueryKey(params);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getProduto>>> = ({
		signal,
	}) => getProduto(params, { signal, ...axiosOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getProduto>>,
		TError,
		TData
	>;
};

export type GetProdutoQueryResult = NonNullable<
	Awaited<ReturnType<typeof getProduto>>
>;
export type GetProdutoQueryError = AxiosError<unknown>;

export function useGetProduto<
	TData = Awaited<ReturnType<typeof getProduto>>,
	TError = AxiosError<unknown>,
>(
	params?: MaybeRef<GetProdutoParams>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getProduto>>, TError, TData>
		>;
		axios?: AxiosRequestConfig;
	},
	queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetProdutoQueryOptions(params, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = unref(queryOptions).queryKey as DataTag<
		QueryKey,
		TData,
		TError
	>;

	return query;
}

/**
 * Retorna um Produto pelo Slug
 */
export const getProdutoSlug = (
	slug: MaybeRef<string>,
	options?: AxiosRequestConfig,
): Promise<AxiosResponse<GetProdutoSlug200>> => {
	slug = unref(slug);

	return axios.default.get(`http://127.0.0.1:1234/produto/${slug}`, options);
};

export const getGetProdutoSlugQueryKey = (slug: MaybeRef<string>) => {
	return ["http:", "127.0.0.1:1234", "produto", slug] as const;
};

export const getGetProdutoSlugQueryOptions = <
	TData = Awaited<ReturnType<typeof getProdutoSlug>>,
	TError = AxiosError<GetProdutoSlug404>,
>(
	slug: MaybeRef<string>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getProdutoSlug>>, TError, TData>
		>;
		axios?: AxiosRequestConfig;
	},
) => {
	const { query: queryOptions, axios: axiosOptions } = options ?? {};

	const queryKey = getGetProdutoSlugQueryKey(slug);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getProdutoSlug>>> = ({
		signal,
	}) => getProdutoSlug(slug, { signal, ...axiosOptions });

	return {
		queryKey,
		queryFn,
		enabled: computed(() => unref(slug) !== null && unref(slug) !== undefined),
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof getProdutoSlug>>,
		TError,
		TData
	>;
};

export type GetProdutoSlugQueryResult = NonNullable<
	Awaited<ReturnType<typeof getProdutoSlug>>
>;
export type GetProdutoSlugQueryError = AxiosError<GetProdutoSlug404>;

export function useGetProdutoSlug<
	TData = Awaited<ReturnType<typeof getProdutoSlug>>,
	TError = AxiosError<GetProdutoSlug404>,
>(
	slug: MaybeRef<string>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getProdutoSlug>>, TError, TData>
		>;
		axios?: AxiosRequestConfig;
	},
	queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetProdutoSlugQueryOptions(slug, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = unref(queryOptions).queryKey as DataTag<
		QueryKey,
		TData,
		TError
	>;

	return query;
}

/**
 * Cadastra um comentario e uma avaliação a um produto
 */
export const postProdutoIdProdutoComments = (
	idProduto: MaybeRef<number>,
	postProdutoIdProdutoCommentsBody: MaybeRef<PostProdutoIdProdutoCommentsBody>,
	options?: AxiosRequestConfig,
): Promise<AxiosResponse<PostProdutoIdProdutoComments200>> => {
	idProduto = unref(idProduto);
	postProdutoIdProdutoCommentsBody = unref(postProdutoIdProdutoCommentsBody);

	return axios.default.post(
		`http://127.0.0.1:1234/produto/${idProduto}/comments`,
		postProdutoIdProdutoCommentsBody,
		options,
	);
};

export const getPostProdutoIdProdutoCommentsMutationOptions = <
	TError = AxiosError<PostProdutoIdProdutoComments401>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postProdutoIdProdutoComments>>,
		TError,
		{ idProduto: number; data: PostProdutoIdProdutoCommentsBody },
		TContext
	>;
	axios?: AxiosRequestConfig;
}): UseMutationOptions<
	Awaited<ReturnType<typeof postProdutoIdProdutoComments>>,
	TError,
	{ idProduto: number; data: PostProdutoIdProdutoCommentsBody },
	TContext
> => {
	const mutationKey = ["postProdutoIdProdutoComments"];
	const { mutation: mutationOptions, axios: axiosOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, axios: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postProdutoIdProdutoComments>>,
		{ idProduto: number; data: PostProdutoIdProdutoCommentsBody }
	> = (props) => {
		const { idProduto, data } = props ?? {};

		return postProdutoIdProdutoComments(idProduto, data, axiosOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type PostProdutoIdProdutoCommentsMutationResult = NonNullable<
	Awaited<ReturnType<typeof postProdutoIdProdutoComments>>
>;
export type PostProdutoIdProdutoCommentsMutationBody =
	PostProdutoIdProdutoCommentsBody;
export type PostProdutoIdProdutoCommentsMutationError =
	AxiosError<PostProdutoIdProdutoComments401>;

export const usePostProdutoIdProdutoComments = <
	TError = AxiosError<PostProdutoIdProdutoComments401>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof postProdutoIdProdutoComments>>,
			TError,
			{ idProduto: number; data: PostProdutoIdProdutoCommentsBody },
			TContext
		>;
		axios?: AxiosRequestConfig;
	},
	queryClient?: QueryClient,
): UseMutationReturnType<
	Awaited<ReturnType<typeof postProdutoIdProdutoComments>>,
	TError,
	{ idProduto: number; data: PostProdutoIdProdutoCommentsBody },
	TContext
> => {
	return useMutation(
		getPostProdutoIdProdutoCommentsMutationOptions(options),
		queryClient,
	);
};
/**
 * Cadatra imagens de Apoio de um Produto
 */
export const postProdutoIdProdutoImages = (
	idProduto: MaybeRef<number>,
	postProdutoIdProdutoImagesBody?: MaybeRef<PostProdutoIdProdutoImagesBody>,
	options?: AxiosRequestConfig,
): Promise<AxiosResponse<PostProdutoIdProdutoImages200>> => {
	idProduto = unref(idProduto);
	postProdutoIdProdutoImagesBody = unref(postProdutoIdProdutoImagesBody);

	return axios.default.post(
		`http://127.0.0.1:1234/produto/${idProduto}/images`,
		postProdutoIdProdutoImagesBody,
		options,
	);
};

export const getPostProdutoIdProdutoImagesMutationOptions = <
	TError = AxiosError<PostProdutoIdProdutoImages400>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postProdutoIdProdutoImages>>,
		TError,
		{ idProduto: number; data?: PostProdutoIdProdutoImagesBody },
		TContext
	>;
	axios?: AxiosRequestConfig;
}): UseMutationOptions<
	Awaited<ReturnType<typeof postProdutoIdProdutoImages>>,
	TError,
	{ idProduto: number; data?: PostProdutoIdProdutoImagesBody },
	TContext
> => {
	const mutationKey = ["postProdutoIdProdutoImages"];
	const { mutation: mutationOptions, axios: axiosOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, axios: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postProdutoIdProdutoImages>>,
		{ idProduto: number; data?: PostProdutoIdProdutoImagesBody }
	> = (props) => {
		const { idProduto, data } = props ?? {};

		return postProdutoIdProdutoImages(idProduto, data, axiosOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type PostProdutoIdProdutoImagesMutationResult = NonNullable<
	Awaited<ReturnType<typeof postProdutoIdProdutoImages>>
>;
export type PostProdutoIdProdutoImagesMutationBody =
	| PostProdutoIdProdutoImagesBody
	| undefined;
export type PostProdutoIdProdutoImagesMutationError =
	AxiosError<PostProdutoIdProdutoImages400>;

export const usePostProdutoIdProdutoImages = <
	TError = AxiosError<PostProdutoIdProdutoImages400>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof postProdutoIdProdutoImages>>,
			TError,
			{ idProduto: number; data?: PostProdutoIdProdutoImagesBody },
			TContext
		>;
		axios?: AxiosRequestConfig;
	},
	queryClient?: QueryClient,
): UseMutationReturnType<
	Awaited<ReturnType<typeof postProdutoIdProdutoImages>>,
	TError,
	{ idProduto: number; data?: PostProdutoIdProdutoImagesBody },
	TContext
> => {
	return useMutation(
		getPostProdutoIdProdutoImagesMutationOptions(options),
		queryClient,
	);
};
/**
 * Endpoint de pesquisa de Produto
 */
export const getProdutoSearch = (
	params: MaybeRef<GetProdutoSearchParams>,
	options?: AxiosRequestConfig,
): Promise<AxiosResponse<GetProdutoSearch200Item[]>> => {
	params = unref(params);

	return axios.default.get(`http://127.0.0.1:1234/produto/search`, {
		...options,
		params: { ...unref(params), ...options?.params },
	});
};

export const getGetProdutoSearchQueryKey = (
	params?: MaybeRef<GetProdutoSearchParams>,
) => {
	return [
		"http:",
		"127.0.0.1:1234",
		"produto",
		"search",
		...(params ? [params] : []),
	] as const;
};

export const getGetProdutoSearchQueryOptions = <
	TData = Awaited<ReturnType<typeof getProdutoSearch>>,
	TError = AxiosError<unknown>,
>(
	params: MaybeRef<GetProdutoSearchParams>,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getProdutoSearch>>,
				TError,
				TData
			>
		>;
		axios?: AxiosRequestConfig;
	},
) => {
	const { query: queryOptions, axios: axiosOptions } = options ?? {};

	const queryKey = getGetProdutoSearchQueryKey(params);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getProdutoSearch>>
	> = ({ signal }) => getProdutoSearch(params, { signal, ...axiosOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getProdutoSearch>>,
		TError,
		TData
	>;
};

export type GetProdutoSearchQueryResult = NonNullable<
	Awaited<ReturnType<typeof getProdutoSearch>>
>;
export type GetProdutoSearchQueryError = AxiosError<unknown>;

export function useGetProdutoSearch<
	TData = Awaited<ReturnType<typeof getProdutoSearch>>,
	TError = AxiosError<unknown>,
>(
	params: MaybeRef<GetProdutoSearchParams>,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getProdutoSearch>>,
				TError,
				TData
			>
		>;
		axios?: AxiosRequestConfig;
	},
	queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetProdutoSearchQueryOptions(params, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = unref(queryOptions).queryKey as DataTag<
		QueryKey,
		TData,
		TError
	>;

	return query;
}
