/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * API Do e-cornance
 * OpenAPI spec version: 1.0.0
 */
export type PostRegistroBody = {
	/** @maxLength 100 */
	nome: string;
	/** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
	email: string;
	/**
	 * @minLength 6
	 * @maxLength 100
	 */
	senha: string;
};

/**
 * Sucesso
 */
export type PostRegistro201 = {
	menssagem: string;
};

export type PostRegistro400StatusCode =
	(typeof PostRegistro400StatusCode)[keyof typeof PostRegistro400StatusCode];

export const PostRegistro400StatusCode = {
	NUMBER_400: 400,
} as const;

export type PostRegistro400Error =
	(typeof PostRegistro400Error)[keyof typeof PostRegistro400Error];

export const PostRegistro400Error = {
	Bad_Request: "Bad Request",
} as const;

/**
 * Requisição inválida
 */
export type PostRegistro400 = {
	statusCode: PostRegistro400StatusCode;
	error: PostRegistro400Error;
	message: string;
};

export type PostLoginBody = {
	/** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
	email: string;
	senha: string;
};

/**
 * Sucesso
 */
export type PostLogin201 = {
	menssagem: string;
};

export type PostLogin401StatusCode =
	(typeof PostLogin401StatusCode)[keyof typeof PostLogin401StatusCode];

export const PostLogin401StatusCode = {
	NUMBER_401: 401,
} as const;

export type PostLogin401Error =
	(typeof PostLogin401Error)[keyof typeof PostLogin401Error];

export const PostLogin401Error = {
	Unauthorized: "Unauthorized",
} as const;

/**
 * Não autorizado
 */
export type PostLogin401 = {
	statusCode: PostLogin401StatusCode;
	error: PostLogin401Error;
	message: string;
};

/**
 * Sucesso
 */
export type PostRefresh201 = {
	menssagem: string;
};

export type PostRefresh401StatusCode =
	(typeof PostRefresh401StatusCode)[keyof typeof PostRefresh401StatusCode];

export const PostRefresh401StatusCode = {
	NUMBER_401: 401,
} as const;

export type PostRefresh401Error =
	(typeof PostRefresh401Error)[keyof typeof PostRefresh401Error];

export const PostRefresh401Error = {
	Unauthorized: "Unauthorized",
} as const;

/**
 * Não autorizado
 */
export type PostRefresh401 = {
	statusCode: PostRefresh401StatusCode;
	error: PostRefresh401Error;
	message: string;
};

export type GetEu200Tipo = (typeof GetEu200Tipo)[keyof typeof GetEu200Tipo];

export const GetEu200Tipo = {
	PADRAO: "PADRAO",
	ADMIN: "ADMIN",
} as const;

/**
 * Dados Do Usuario
 */
export type GetEu200 = {
	nome: string;
	/** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
	email: string;
	tipo: GetEu200Tipo;
};

export type GetEu401StatusCode =
	(typeof GetEu401StatusCode)[keyof typeof GetEu401StatusCode];

export const GetEu401StatusCode = {
	NUMBER_401: 401,
} as const;

export type GetEu401Error = (typeof GetEu401Error)[keyof typeof GetEu401Error];

export const GetEu401Error = {
	Unauthorized: "Unauthorized",
} as const;

/**
 * Não autorizado
 */
export type GetEu401 = {
	statusCode: GetEu401StatusCode;
	error: GetEu401Error;
	message: string;
};

export type PostProdutoBody = {
	nome: string;
	descricao: string;
	/** @maximum 9007199254740991 */
	idTipo: number;
	foto?: Blob;
	/** define se deve pular ou não o serviço de remoção de fundo */
	skipRMBG?: boolean;
	/** @maximum 9007199254740991 */
	precoCentavos: number;
};

export type PostProduto200Data = {
	imagem: string;
	id: number;
	nome: string;
	slug: string;
};

export type PostProduto200 = {
	idJob?: string;
	data: PostProduto200Data;
};

export type PostProduto401StatusCode =
	(typeof PostProduto401StatusCode)[keyof typeof PostProduto401StatusCode];

export const PostProduto401StatusCode = {
	NUMBER_401: 401,
} as const;

export type PostProduto401Error =
	(typeof PostProduto401Error)[keyof typeof PostProduto401Error];

export const PostProduto401Error = {
	Unauthorized: "Unauthorized",
} as const;

/**
 * Não autorizado
 */
export type PostProduto401 = {
	statusCode: PostProduto401StatusCode;
	error: PostProduto401Error;
	message: string;
};

export type GetProdutoParams = {
	lastProduto?: number;
	limit?: number;
	/**
	 * O preco minimo a ser filtrado
	 * @exclusiveMinimum 0
	 */
	minPreco?: number;
	/**
	 * a minima avaliação media a ser filtrada
	 * @exclusiveMinimum 0
	 */
	minAvalicacao?: number;
	/**
	 * O preco minimo a ser filtrado
	 * @exclusiveMinimum 0
	 */
	maxPreco?: number;
	/**
	 * a minima avaliação media a ser filtrada
	 * @exclusiveMinimum 0
	 */
	maxAvalicacao?: number;
};

export type GetProduto200DataItem = {
	id: number;
	nome: string;
	precoEmCentavos: number;
	slug: string;
	imagem: string;
	/** @nullable */
	corDestaque: string | null;
	avaliacaoMedia: number;
	/** @nullable */
	tipo: string | null;
};

export type GetProduto200 = {
	total: number;
	limit: number;
	seTemProximo: boolean;
	data: GetProduto200DataItem[];
};

export type GetProdutoStatusIdJob200 = {
	/** @maximum 9007199254740991 */
	progress: number;
	idJob: string;
	return: unknown;
};

export type GetProdutoStatusIdJob404StatusCode =
	(typeof GetProdutoStatusIdJob404StatusCode)[keyof typeof GetProdutoStatusIdJob404StatusCode];

export const GetProdutoStatusIdJob404StatusCode = {
	NUMBER_404: 404,
} as const;

export type GetProdutoStatusIdJob404Error =
	(typeof GetProdutoStatusIdJob404Error)[keyof typeof GetProdutoStatusIdJob404Error];

export const GetProdutoStatusIdJob404Error = {
	Not_Found: "Not Found",
} as const;

/**
 * Não encontrado
 */
export type GetProdutoStatusIdJob404 = {
	statusCode: GetProdutoStatusIdJob404StatusCode;
	error: GetProdutoStatusIdJob404Error;
	message: string;
};

export type PostProdutoRetryBody = {
	/**
	 * Id do job de remo
	 * @maximum 9007199254740991
	 */
	idJob: number;
};

export type PostProdutoRetry200 = {
	jobId: number;
};

export type PostProdutoRetry400StatusCode =
	(typeof PostProdutoRetry400StatusCode)[keyof typeof PostProdutoRetry400StatusCode];

export const PostProdutoRetry400StatusCode = {
	NUMBER_400: 400,
} as const;

export type PostProdutoRetry400Error =
	(typeof PostProdutoRetry400Error)[keyof typeof PostProdutoRetry400Error];

export const PostProdutoRetry400Error = {
	Bad_Request: "Bad Request",
} as const;

/**
 * Requisição inválida
 */
export type PostProdutoRetry400 = {
	statusCode: PostProdutoRetry400StatusCode;
	error: PostProdutoRetry400Error;
	message: string;
};

export type PostProdutoRetry404StatusCode =
	(typeof PostProdutoRetry404StatusCode)[keyof typeof PostProdutoRetry404StatusCode];

export const PostProdutoRetry404StatusCode = {
	NUMBER_404: 404,
} as const;

export type PostProdutoRetry404Error =
	(typeof PostProdutoRetry404Error)[keyof typeof PostProdutoRetry404Error];

export const PostProdutoRetry404Error = {
	Not_Found: "Not Found",
} as const;

/**
 * Não encontrado
 */
export type PostProdutoRetry404 = {
	statusCode: PostProdutoRetry404StatusCode;
	error: PostProdutoRetry404Error;
	message: string;
};

export type GetProdutoSlug200ComentariosItem = {
	/** @nullable */
	id: number | null;
	comentador: string;
	/** @nullable */
	estrelas: number | null;
	/** @nullable */
	texto: string | null;
};

export type GetProdutoSlug200 = {
	id: number;
	nome: string;
	slug: string;
	imagem: string;
	/** @nullable */
	cor: string | null;
	avaliacaoMedia: number;
	/** @nullable */
	tipo: string | null;
	comentarios: GetProdutoSlug200ComentariosItem[];
};

export type GetProdutoSlug404StatusCode =
	(typeof GetProdutoSlug404StatusCode)[keyof typeof GetProdutoSlug404StatusCode];

export const GetProdutoSlug404StatusCode = {
	NUMBER_404: 404,
} as const;

export type GetProdutoSlug404Error =
	(typeof GetProdutoSlug404Error)[keyof typeof GetProdutoSlug404Error];

export const GetProdutoSlug404Error = {
	Not_Found: "Not Found",
} as const;

/**
 * Não encontrado
 */
export type GetProdutoSlug404 = {
	statusCode: GetProdutoSlug404StatusCode;
	error: GetProdutoSlug404Error;
	message: string;
};

export type PostProdutoIdProdutoCommentsBody = {
	descricao: string;
	/**
	 * @minimum 0
	 * @maximum 5
	 */
	estrelas: number;
};

export type PostProdutoIdProdutoComments200 = {
	idProduto: number;
	estrelas: number;
	id: number;
	/** @nullable */
	createdAt: string | null;
	/** @nullable */
	updatedAt: string | null;
	idUsuario: number;
	texto: string;
};

export type PostProdutoIdProdutoComments401StatusCode =
	(typeof PostProdutoIdProdutoComments401StatusCode)[keyof typeof PostProdutoIdProdutoComments401StatusCode];

export const PostProdutoIdProdutoComments401StatusCode = {
	NUMBER_401: 401,
} as const;

export type PostProdutoIdProdutoComments401Error =
	(typeof PostProdutoIdProdutoComments401Error)[keyof typeof PostProdutoIdProdutoComments401Error];

export const PostProdutoIdProdutoComments401Error = {
	Unauthorized: "Unauthorized",
} as const;

/**
 * Não autorizado
 */
export type PostProdutoIdProdutoComments401 = {
	statusCode: PostProdutoIdProdutoComments401StatusCode;
	error: PostProdutoIdProdutoComments401Error;
	message: string;
};

export type PostProdutoIdProdutoImagesBody = {
	files?: Blob[];
};

export type PostProdutoIdProdutoImages200ImgsItem = {
	id: number;
	/** @nullable */
	createdAt: string | null;
	idProduto: number;
	caminho: string;
	/** @nullable */
	ordem: number | null;
};

export type PostProdutoIdProdutoImages200 = {
	idProduto: number;
	imgs: PostProdutoIdProdutoImages200ImgsItem[];
};

export type PostProdutoIdProdutoImages400StatusCode =
	(typeof PostProdutoIdProdutoImages400StatusCode)[keyof typeof PostProdutoIdProdutoImages400StatusCode];

export const PostProdutoIdProdutoImages400StatusCode = {
	NUMBER_400: 400,
} as const;

export type PostProdutoIdProdutoImages400Error =
	(typeof PostProdutoIdProdutoImages400Error)[keyof typeof PostProdutoIdProdutoImages400Error];

export const PostProdutoIdProdutoImages400Error = {
	Bad_Request: "Bad Request",
} as const;

/**
 * Requisição inválida
 */
export type PostProdutoIdProdutoImages400 = {
	statusCode: PostProdutoIdProdutoImages400StatusCode;
	error: PostProdutoIdProdutoImages400Error;
	message: string;
};

export type GetProdutoSearchParams = {
	/**
	 * query de busca
	 * @minLength 3
	 */
	q: string;
};

export type GetProdutoSearch200Item = {
	id: number;
	nome: string;
	/** @nullable */
	descricao: string | null;
	imagem: string;
	slug: string;
	precoCentavos: number;
};

export type GetTipoSlugParams = {
	lastProduto?: number;
	limit?: number;
	/**
	 * O preco minimo a ser filtrado
	 * @exclusiveMinimum 0
	 */
	minPreco?: number;
	/**
	 * a minima avaliação media a ser filtrada
	 * @exclusiveMinimum 0
	 */
	minAvalicacao?: number;
	/**
	 * O preco minimo a ser filtrado
	 * @exclusiveMinimum 0
	 */
	maxPreco?: number;
	/**
	 * a minima avaliação media a ser filtrada
	 * @exclusiveMinimum 0
	 */
	maxAvalicacao?: number;
};

export type GetTipoSlug200DataItem = {
	id: number;
	nome: string;
	precoinCents: number;
	slug: string;
	imagem: string;
	/** @nullable */
	corDestaque: string | null;
	avaliacaoMedia: unknown;
	tipo: string;
};

export type GetTipoSlug200 = {
	data: GetTipoSlug200DataItem[];
	seTemProximo: boolean;
};

export type GetTipoParams = {
	lastTipo?: number;
	limit?: number;
};

export type GetTipo200DataItem = {
	id: number;
	nome: string;
	slug: string;
};

export type GetTipo200 = {
	data: GetTipo200DataItem[];
	seTemProximo: boolean;
};

export type PostTipoBody = {
	nome: string;
};
