/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * API Do e-cornance
 * OpenAPI spec version: 1.0.0
 */

import type {
	DataTag,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UseMutationOptions,
	UseMutationReturnType,
	UseQueryOptions,
	UseQueryReturnType,
} from "@tanstack/vue-query";
import { useMutation, useQuery } from "@tanstack/vue-query";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";
import * as axios from "axios";
import type { MaybeRef } from "vue";
import { computed, unref } from "vue";

import type {
	GetTipo200,
	GetTipoParams,
	GetTipoSlug200,
	GetTipoSlugParams,
	PostTipoBody,
} from "../index.schemas";

/**
 * Retorna o tipo pelo slug e seus Produtos
 */
export const getTipoSlug = (
	slug: MaybeRef<string>,
	params?: MaybeRef<GetTipoSlugParams>,
	options?: AxiosRequestConfig,
): Promise<AxiosResponse<GetTipoSlug200>> => {
	slug = unref(slug);
	params = unref(params);

	return axios.default.get(`http://127.0.0.1:1234/tipo/${slug}`, {
		...options,
		params: { ...unref(params), ...options?.params },
	});
};

export const getGetTipoSlugQueryKey = (
	slug: MaybeRef<string>,
	params?: MaybeRef<GetTipoSlugParams>,
) => {
	return [
		"http:",
		"127.0.0.1:1234",
		"tipo",
		slug,
		...(params ? [params] : []),
	] as const;
};

export const getGetTipoSlugQueryOptions = <
	TData = Awaited<ReturnType<typeof getTipoSlug>>,
	TError = AxiosError<unknown>,
>(
	slug: MaybeRef<string>,
	params?: MaybeRef<GetTipoSlugParams>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getTipoSlug>>, TError, TData>
		>;
		axios?: AxiosRequestConfig;
	},
) => {
	const { query: queryOptions, axios: axiosOptions } = options ?? {};

	const queryKey = getGetTipoSlugQueryKey(slug, params);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getTipoSlug>>> = ({
		signal,
	}) => getTipoSlug(slug, params, { signal, ...axiosOptions });

	return {
		queryKey,
		queryFn,
		enabled: computed(() => unref(slug) !== null && unref(slug) !== undefined),
		...queryOptions,
	} as UseQueryOptions<Awaited<ReturnType<typeof getTipoSlug>>, TError, TData>;
};

export type GetTipoSlugQueryResult = NonNullable<
	Awaited<ReturnType<typeof getTipoSlug>>
>;
export type GetTipoSlugQueryError = AxiosError<unknown>;

export function useGetTipoSlug<
	TData = Awaited<ReturnType<typeof getTipoSlug>>,
	TError = AxiosError<unknown>,
>(
	slug: MaybeRef<string>,
	params?: MaybeRef<GetTipoSlugParams>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getTipoSlug>>, TError, TData>
		>;
		axios?: AxiosRequestConfig;
	},
	queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetTipoSlugQueryOptions(slug, params, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = unref(queryOptions).queryKey as DataTag<
		QueryKey,
		TData,
		TError
	>;

	return query;
}

/**
 * Retorna uma lista de tipos
 */
export const getTipo = (
	params?: MaybeRef<GetTipoParams>,
	options?: AxiosRequestConfig,
): Promise<AxiosResponse<GetTipo200>> => {
	params = unref(params);

	return axios.default.get(`http://127.0.0.1:1234/tipo/`, {
		...options,
		params: { ...unref(params), ...options?.params },
	});
};

export const getGetTipoQueryKey = (params?: MaybeRef<GetTipoParams>) => {
	return [
		"http:",
		"127.0.0.1:1234",
		"tipo",
		...(params ? [params] : []),
	] as const;
};

export const getGetTipoQueryOptions = <
	TData = Awaited<ReturnType<typeof getTipo>>,
	TError = AxiosError<unknown>,
>(
	params?: MaybeRef<GetTipoParams>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getTipo>>, TError, TData>
		>;
		axios?: AxiosRequestConfig;
	},
) => {
	const { query: queryOptions, axios: axiosOptions } = options ?? {};

	const queryKey = getGetTipoQueryKey(params);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getTipo>>> = ({
		signal,
	}) => getTipo(params, { signal, ...axiosOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getTipo>>,
		TError,
		TData
	>;
};

export type GetTipoQueryResult = NonNullable<
	Awaited<ReturnType<typeof getTipo>>
>;
export type GetTipoQueryError = AxiosError<unknown>;

export function useGetTipo<
	TData = Awaited<ReturnType<typeof getTipo>>,
	TError = AxiosError<unknown>,
>(
	params?: MaybeRef<GetTipoParams>,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getTipo>>, TError, TData>
		>;
		axios?: AxiosRequestConfig;
	},
	queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetTipoQueryOptions(params, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = unref(queryOptions).queryKey as DataTag<
		QueryKey,
		TData,
		TError
	>;

	return query;
}

/**
 * Cadastra um tipo novo
 */
export const postTipo = (
	postTipoBody: MaybeRef<PostTipoBody>,
	options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
	postTipoBody = unref(postTipoBody);

	return axios.default.post(
		`http://127.0.0.1:1234/tipo/`,
		postTipoBody,
		options,
	);
};

export const getPostTipoMutationOptions = <
	TError = AxiosError<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postTipo>>,
		TError,
		{ data: PostTipoBody },
		TContext
	>;
	axios?: AxiosRequestConfig;
}): UseMutationOptions<
	Awaited<ReturnType<typeof postTipo>>,
	TError,
	{ data: PostTipoBody },
	TContext
> => {
	const mutationKey = ["postTipo"];
	const { mutation: mutationOptions, axios: axiosOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, axios: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postTipo>>,
		{ data: PostTipoBody }
	> = (props) => {
		const { data } = props ?? {};

		return postTipo(data, axiosOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type PostTipoMutationResult = NonNullable<
	Awaited<ReturnType<typeof postTipo>>
>;
export type PostTipoMutationBody = PostTipoBody;
export type PostTipoMutationError = AxiosError<unknown>;

export const usePostTipo = <TError = AxiosError<unknown>, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof postTipo>>,
			TError,
			{ data: PostTipoBody },
			TContext
		>;
		axios?: AxiosRequestConfig;
	},
	queryClient?: QueryClient,
): UseMutationReturnType<
	Awaited<ReturnType<typeof postTipo>>,
	TError,
	{ data: PostTipoBody },
	TContext
> => {
	return useMutation(getPostTipoMutationOptions(options), queryClient);
};
