/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * API Do e-cornance
 * OpenAPI spec version: 1.0.0
 */

import type {
	DataTag,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UseMutationOptions,
	UseMutationReturnType,
	UseQueryOptions,
	UseQueryReturnType,
} from "@tanstack/vue-query";
import { useMutation, useQuery } from "@tanstack/vue-query";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";
import * as axios from "axios";
import type { MaybeRef } from "vue";
import { unref } from "vue";

import type {
	GetEu200,
	GetEu401,
	PostLogin201,
	PostLogin401,
	PostLoginBody,
	PostRefresh201,
	PostRefresh401,
	PostRegistro201,
	PostRegistro400,
	PostRegistroBody,
} from "../index.schemas";

/**
 * Rota para registrar um novo usuário
 */
export const postRegistro = (
	postRegistroBody: MaybeRef<PostRegistroBody>,
	options?: AxiosRequestConfig,
): Promise<AxiosResponse<PostRegistro201>> => {
	postRegistroBody = unref(postRegistroBody);

	return axios.default.post(
		`http://127.0.0.1:1234/registro`,
		postRegistroBody,
		options,
	);
};

export const getPostRegistroMutationOptions = <
	TError = AxiosError<PostRegistro400>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postRegistro>>,
		TError,
		{ data: PostRegistroBody },
		TContext
	>;
	axios?: AxiosRequestConfig;
}): UseMutationOptions<
	Awaited<ReturnType<typeof postRegistro>>,
	TError,
	{ data: PostRegistroBody },
	TContext
> => {
	const mutationKey = ["postRegistro"];
	const { mutation: mutationOptions, axios: axiosOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, axios: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postRegistro>>,
		{ data: PostRegistroBody }
	> = (props) => {
		const { data } = props ?? {};

		return postRegistro(data, axiosOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type PostRegistroMutationResult = NonNullable<
	Awaited<ReturnType<typeof postRegistro>>
>;
export type PostRegistroMutationBody = PostRegistroBody;
export type PostRegistroMutationError = AxiosError<PostRegistro400>;

export const usePostRegistro = <
	TError = AxiosError<PostRegistro400>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof postRegistro>>,
			TError,
			{ data: PostRegistroBody },
			TContext
		>;
		axios?: AxiosRequestConfig;
	},
	queryClient?: QueryClient,
): UseMutationReturnType<
	Awaited<ReturnType<typeof postRegistro>>,
	TError,
	{ data: PostRegistroBody },
	TContext
> => {
	return useMutation(getPostRegistroMutationOptions(options), queryClient);
};
export const postLogin = (
	postLoginBody: MaybeRef<PostLoginBody>,
	options?: AxiosRequestConfig,
): Promise<AxiosResponse<PostLogin201>> => {
	postLoginBody = unref(postLoginBody);

	return axios.default.post(
		`http://127.0.0.1:1234/login`,
		postLoginBody,
		options,
	);
};

export const getPostLoginMutationOptions = <
	TError = AxiosError<PostLogin401>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postLogin>>,
		TError,
		{ data: PostLoginBody },
		TContext
	>;
	axios?: AxiosRequestConfig;
}): UseMutationOptions<
	Awaited<ReturnType<typeof postLogin>>,
	TError,
	{ data: PostLoginBody },
	TContext
> => {
	const mutationKey = ["postLogin"];
	const { mutation: mutationOptions, axios: axiosOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, axios: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postLogin>>,
		{ data: PostLoginBody }
	> = (props) => {
		const { data } = props ?? {};

		return postLogin(data, axiosOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type PostLoginMutationResult = NonNullable<
	Awaited<ReturnType<typeof postLogin>>
>;
export type PostLoginMutationBody = PostLoginBody;
export type PostLoginMutationError = AxiosError<PostLogin401>;

export const usePostLogin = <
	TError = AxiosError<PostLogin401>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof postLogin>>,
			TError,
			{ data: PostLoginBody },
			TContext
		>;
		axios?: AxiosRequestConfig;
	},
	queryClient?: QueryClient,
): UseMutationReturnType<
	Awaited<ReturnType<typeof postLogin>>,
	TError,
	{ data: PostLoginBody },
	TContext
> => {
	return useMutation(getPostLoginMutationOptions(options), queryClient);
};
export const postRefresh = (
	options?: AxiosRequestConfig,
): Promise<AxiosResponse<PostRefresh201>> => {
	return axios.default.post(
		`http://127.0.0.1:1234/refresh`,
		undefined,
		options,
	);
};

export const getPostRefreshMutationOptions = <
	TError = AxiosError<PostRefresh401>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postRefresh>>,
		TError,
		void,
		TContext
	>;
	axios?: AxiosRequestConfig;
}): UseMutationOptions<
	Awaited<ReturnType<typeof postRefresh>>,
	TError,
	void,
	TContext
> => {
	const mutationKey = ["postRefresh"];
	const { mutation: mutationOptions, axios: axiosOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, axios: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postRefresh>>,
		void
	> = () => {
		return postRefresh(axiosOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type PostRefreshMutationResult = NonNullable<
	Awaited<ReturnType<typeof postRefresh>>
>;

export type PostRefreshMutationError = AxiosError<PostRefresh401>;

export const usePostRefresh = <
	TError = AxiosError<PostRefresh401>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof postRefresh>>,
			TError,
			void,
			TContext
		>;
		axios?: AxiosRequestConfig;
	},
	queryClient?: QueryClient,
): UseMutationReturnType<
	Awaited<ReturnType<typeof postRefresh>>,
	TError,
	void,
	TContext
> => {
	return useMutation(getPostRefreshMutationOptions(options), queryClient);
};
export const getEu = (
	options?: AxiosRequestConfig,
): Promise<AxiosResponse<GetEu200>> => {
	return axios.default.get(`http://127.0.0.1:1234/eu`, options);
};

export const getGetEuQueryKey = () => {
	return ["http:", "127.0.0.1:1234", "eu"] as const;
};

export const getGetEuQueryOptions = <
	TData = Awaited<ReturnType<typeof getEu>>,
	TError = AxiosError<GetEu401>,
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof getEu>>, TError, TData>
	>;
	axios?: AxiosRequestConfig;
}) => {
	const { query: queryOptions, axios: axiosOptions } = options ?? {};

	const queryKey = getGetEuQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getEu>>> = ({
		signal,
	}) => getEu({ signal, ...axiosOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getEu>>,
		TError,
		TData
	>;
};

export type GetEuQueryResult = NonNullable<Awaited<ReturnType<typeof getEu>>>;
export type GetEuQueryError = AxiosError<GetEu401>;

export function useGetEu<
	TData = Awaited<ReturnType<typeof getEu>>,
	TError = AxiosError<GetEu401>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getEu>>, TError, TData>
		>;
		axios?: AxiosRequestConfig;
	},
	queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetEuQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = unref(queryOptions).queryKey as DataTag<
		QueryKey,
		TData,
		TError
	>;

	return query;
}
