CREATE TYPE "ROLES" AS ENUM (
  'PADRAO',
  'ADMIN'
);

CREATE TABLE "usuarios" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now()),
  "tipo" "ROLES" NOT NULL DEFAULT 'PADRAO',
  "email" varchar(190) UNIQUE NOT NULL ,
  "senha" varchar(190) NOT NULL
  
);

CREATE TABLE "enderecos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now()),
  "id_usuario" integer NOT NULL,
  "cep" varchar(10) NOT NULL,
  "numero" integer,
  "complemento" varchar(190),
  "estado" varchar(190) NOT NULL,
  "pais" varchar(190) NOT NULL DEFAULT 'Brasil',
  "municipio" varchar(190) NOT NULL,
  "rua" varchar(190) NOT NULL
);

CREATE TABLE "tipos_produtos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now()),
  "nome" varchar(255) NOT NULL,
  "slug" varchar(255) UNIQUE NOT NULL
);

CREATE TABLE "produtos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now()),
  "nome" varchar(180) NOT NULL,
  "descricao" text,
  "id_tipo" int NOT NULL,
  "imagem_principal" varchar(255),
  "slug" varchar(255) UNIQUE NOT NULL,
  "preco_centavos" integer NOT NULL
);

CREATE TABLE "imgs_produtos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_produto" int NOT NULL,
  "caminho" varchar(255) NOT NULL,
  "ordem" int DEFAULT 0,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "comentarios" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now()),
  "id_produto" int NOT NULL,
  "id_usuario" int NOT NULL,
  "texto" text NOT NULL,
  "estrelas" int NOT NULL
);

CREATE TABLE "carrinhos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now()),
  "id_usuario" int UNIQUE NOT NULL
);

CREATE TABLE "itens_carrinho" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_carrinho" int NOT NULL,
  "id_produto" int NOT NULL,
  "quantidade" int NOT NULL DEFAULT 1,
  "preco_centavos_snapshot" int NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE UNIQUE INDEX ON "comentarios" ("id_produto", "id_usuario");

CREATE UNIQUE INDEX ON "itens_carrinho" ("id_carrinho", "id_produto");

COMMENT ON COLUMN "produtos"."preco_centavos" IS 'Preço em centavos, ex: 1500 = R$ 15,00';

COMMENT ON COLUMN "imgs_produtos"."ordem" IS 'Ordem de exibição';

COMMENT ON COLUMN "comentarios"."estrelas" IS '1 a 5';

COMMENT ON COLUMN "carrinhos"."id_usuario" IS '1 carrinho por usuário';

COMMENT ON COLUMN "itens_carrinho"."preco_centavos_snapshot" IS 'Preço quando adicionou ao carrinho';

ALTER TABLE "itens_carrinho" ADD FOREIGN KEY ("id_produto") REFERENCES "produtos" ("id") ON DELETE CASCADE;

ALTER TABLE "usuarios" ADD FOREIGN KEY ("id") REFERENCES "carrinhos" ("id_usuario") ON DELETE CASCADE;

ALTER TABLE "itens_carrinho" ADD FOREIGN KEY ("id_carrinho") REFERENCES "carrinhos" ("id") ON DELETE CASCADE;

ALTER TABLE "comentarios" ADD FOREIGN KEY ("id_usuario") REFERENCES "usuarios" ("id") ON DELETE CASCADE;

ALTER TABLE "comentarios" ADD FOREIGN KEY ("id_produto") REFERENCES "produtos" ("id") ON DELETE CASCADE;

ALTER TABLE "imgs_produtos" ADD FOREIGN KEY ("id_produto") REFERENCES "produtos" ("id") ON DELETE CASCADE;

ALTER TABLE "produtos" ADD FOREIGN KEY ("id_tipo") REFERENCES "tipos_produtos" ("id");

ALTER TABLE "enderecos" ADD FOREIGN KEY ("id_usuario") REFERENCES "usuarios" ("id") ON DELETE CASCADE;
