CREATE TYPE "public"."ROLES" AS ENUM('PADRAO',
  'ADMIN'); --> statement-breakpoint
CREATE TABLE "carrinhos" ("id" integer PRIMARY KEY GENERATED BY DEFAULT AS
  IDENTITY (sequence name "carrinhos_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE
  2147483647 START WITH 1 CACHE 1), "created_at" timestamp DEFAULT now(),
  "updated_at" timestamp DEFAULT now(), "id_usuario" integer NOT NULL,
  CONSTRAINT "carrinhos_id_usuario_key" UNIQUE("id_usuario"));
--> statement-breakpoint
CREATE TABLE "comentarios" ("id" integer PRIMARY KEY GENERATED BY DEFAULT AS
  IDENTITY (sequence name "comentarios_id_seq" INCREMENT BY 1 MINVALUE 1
  MAXVALUE 2147483647 START WITH 1 CACHE 1), "created_at" timestamp DEFAULT
  now(), "updated_at" timestamp DEFAULT now(), "id_produto" integer NOT NULL,
  "id_usuario" integer NOT NULL, "texto" text NOT NULL, "estrelas" integer NOT
  NULL);
--> statement-breakpoint
CREATE TABLE "enderecos" ("id" integer PRIMARY KEY GENERATED BY DEFAULT AS
  IDENTITY (sequence name "enderecos_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE
  2147483647 START WITH 1 CACHE 1), "created_at" timestamp DEFAULT now(),
  "updated_at" timestamp DEFAULT now(), "id_usuario" integer NOT NULL, "cep"
  varchar(10) NOT NULL, "numero" integer, "complemento" varchar(190));
--> statement-breakpoint
CREATE TABLE "imgs_produtos" ("id" integer PRIMARY KEY GENERATED BY DEFAULT AS
  IDENTITY (sequence name "imgs_produtos_id_seq" INCREMENT BY 1 MINVALUE 1
  MAXVALUE 2147483647 START WITH 1 CACHE 1), "id_produto" integer NOT NULL,
  "caminho" varchar(255) NOT NULL, "ordem" integer DEFAULT 0, "created_at"
  timestamp DEFAULT now());
--> statement-breakpoint
CREATE TABLE "itens_carrinho" ("id" integer PRIMARY KEY GENERATED BY DEFAULT AS
  IDENTITY (sequence name "itens_carrinho_id_seq" INCREMENT BY 1 MINVALUE 1
  MAXVALUE 2147483647 START WITH 1 CACHE 1), "id_carrinho" integer NOT NULL,
  "id_produto" integer NOT NULL, "quantidade" integer DEFAULT 1 NOT NULL,
  "preco_centavos_snapshot" integer NOT NULL, "created_at" timestamp DEFAULT
  now(), "updated_at" timestamp DEFAULT now());
--> statement-breakpoint
CREATE TABLE "produtos" ("id" integer PRIMARY KEY GENERATED BY DEFAULT AS
  IDENTITY (sequence name "produtos_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE
  2147483647 START WITH 1 CACHE 1), "created_at" timestamp DEFAULT now(),
  "updated_at" timestamp DEFAULT now(), "nome" varchar(180) NOT NULL,
  "descricao" text, "cor_destaque" varchar, "old_image" varchar(255), "id_tipo"
  integer NOT NULL, "imagem_principal" varchar(255) NOT NULL, "slug"
  varchar(255) NOT NULL, "preco_centavos" integer NOT NULL, CONSTRAINT
  "produtos_slug_key" UNIQUE("slug"));
--> statement-breakpoint
CREATE TABLE "tipos_produtos" ("id" integer PRIMARY KEY GENERATED BY DEFAULT AS
  IDENTITY (sequence name "tipos_produtos_id_seq" INCREMENT BY 1 MINVALUE 1
  MAXVALUE 2147483647 START WITH 1 CACHE 1), "created_at" timestamp DEFAULT
  now(), "updated_at" timestamp DEFAULT now(), "nome" varchar(255) NOT NULL,
  "slug" varchar(255) NOT NULL, CONSTRAINT "tipos_produtos_slug_key"
  UNIQUE("slug"));
--> statement-breakpoint
CREATE TABLE "usuarios" ("id" integer PRIMARY KEY GENERATED BY DEFAULT AS
  IDENTITY (sequence name "usuarios_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE
  2147483647 START WITH 1 CACHE 1), "created_at" timestamp DEFAULT now(),
  "updated_at" timestamp DEFAULT now(), "tipo" "ROLES" DEFAULT 'PADRAO' NOT
  NULL, "email" varchar(190) NOT NULL, "nome" varchar(190) NOT NULL, "senha"
  varchar(190) NOT NULL, CONSTRAINT "usuarios_email_key" UNIQUE("email"));
--> statement-breakpoint
ALTER TABLE "carrinhos" ADD CONSTRAINT "carrinhos_id_usuario_fkey" FOREIGN KEY
  ("id_usuario") REFERENCES "public"."usuarios"("id") ON DELETE CASCADE ON
  UPDATE no action; --> statement-breakpoint
ALTER TABLE "comentarios" ADD CONSTRAINT "comentarios_id_usuario_fkey" FOREIGN
  KEY ("id_usuario") REFERENCES "public"."usuarios"("id") ON DELETE CASCADE ON
  UPDATE no action; --> statement-breakpoint
ALTER TABLE "comentarios" ADD CONSTRAINT "comentarios_id_produto_fkey" FOREIGN
  KEY ("id_produto") REFERENCES "public"."produtos"("id") ON DELETE CASCADE ON
  UPDATE no action; --> statement-breakpoint
ALTER TABLE "enderecos" ADD CONSTRAINT "enderecos_id_usuario_fkey" FOREIGN KEY
  ("id_usuario") REFERENCES "public"."usuarios"("id") ON DELETE CASCADE ON
  UPDATE no action; --> statement-breakpoint
ALTER TABLE "imgs_produtos" ADD CONSTRAINT "imgs_produtos_id_produto_fkey"
  FOREIGN KEY ("id_produto") REFERENCES "public"."produtos"("id") ON DELETE
  CASCADE ON UPDATE no action; --> statement-breakpoint
ALTER TABLE "itens_carrinho" ADD CONSTRAINT "itens_carrinho_id_produto_fkey"
  FOREIGN KEY ("id_produto") REFERENCES "public"."produtos"("id") ON DELETE
  CASCADE ON UPDATE no action; --> statement-breakpoint
ALTER TABLE "itens_carrinho" ADD CONSTRAINT "itens_carrinho_id_carrinho_fkey"
  FOREIGN KEY ("id_carrinho") REFERENCES "public"."carrinhos"("id") ON DELETE
  CASCADE ON UPDATE no action; --> statement-breakpoint
ALTER TABLE "produtos" ADD CONSTRAINT "produtos_id_tipo_fkey" FOREIGN KEY
  ("id_tipo") REFERENCES "public"."tipos_produtos"("id") ON DELETE no action ON
  UPDATE no action; --> statement-breakpoint
CREATE UNIQUE INDEX "itens_carrinho_id_carrinho_id_produto_idx" ON
  "itens_carrinho" USING btree ("id_carrinho" int4_ops,"id_produto"
  int4_ops); --> statement-breakpoint
CREATE INDEX "produtos_slug_idx" ON "produtos" USING btree
  ("slug"); --> statement-breakpoint
CREATE INDEX "tipos_produtos_slug_idx" ON "tipos_produtos" USING btree ("slug");
